image: debian

variables:
  DISTRIBUTIONS: "wheezy,ui70-portal,jessie,ui80-portal,stretch,ui90-portal"

build:
  variables:
    PACKAGE: alertmanager

  stage: test
  script:
    - wget https://github.com/prometheus/alertmanager/releases/download/v0.15.3/alertmanager-0.15.3.linux-amd64.tar.gz
    - tar xzvf alertmanager-0.15.3.linux-amd64.tar.gz
    - mkdir -p data/etc/sv/alertmanager/log/run
    - mkdir -p data/etc/default
    - mkdir -p data/etc/systemd/system/alertmanager.service.d/ 
    - mkdir -p data/usr/share/doc
    - mkdir data/usr/share/alertmanager
    - mkdir data/usr/share/doc/alertmanager
    - mkdir -p data/usr/bin
    - mkdir -p data/lib/systemd/system/
    - cp $PWD/alertmanager.service $PWD/data/lib/systemd/system/
    - cp $PWD/alertmanager-0.15.3.linux-amd64/alertmanager $PWD/data/usr/bin
    - cp $PWD/alertmanager-0.15.3.linux-amd64/amtool $PWD/data/usr/bin
    - cp $PWD/alertmanager-0.15.3.linux-amd64/alertmanager.yml data/etc/
    - touch data/etc/default/alertmanager
    - echo "ARGS="--config.file=/etc/alertmanager.yml"" >> data/etc/default/alertmanager
    - fpm -t deb -n alertmanager -C $PWD/data -s dir -v 0.15.3 
      -m "\"${GITLAB_USER_NAME}\" <${GITLB_USER_EMAIL}>"
      --deb-systemd-restart-after-upgrade
      --deb-user nobody
      --deb-group nogroup
    - rm -r alertmanager-0.15.3.linux-amd64
    - rm alertmanager-0.15.3.linux-amd64.tar.gz
    - rm -r data
