image: debian

variables:
  DISTRIBUTIONS: "wheezy,ui70-portal,jessie,ui80-portal,stretch,ui90-portal"

build:
  variables:
    PACKAGE: alertmanager

  stage: test
  script:
    - apt-get update -y
    - apt-get install ruby ruby-dev rubygems build-essential -y
    - apt-get update -y 
    - gem install --no-ri --no-rdoc fpm
    - fpm -t deb -n alertmanager -s dir -C $PWD/data -v 0.15.3  
      -m "\"${GITLAB_USER_NAME}\" <${GITLB_USER_EMAIL}>"
      --deb-systemd-restart-after-upgrade
      --deb-user nobody
      --deb-group nogroup
